var dict = Dictionary();

dict.put(\mainX, 300);
dict.put(\mainY, 150);
dict.put(\mainWidth, 800);
dict.put(\mainHeight, 600);
dict.put(\mainBackground, Color.gray(0.6));
dict.put(\leftClick, 0);
dict.put(\rightClick, 1);
dict.put(\title, "Main");
dict.put(\menuFont, Font("Monaco", 16));
dict.put(\synthFont, Font("Monaco", 14));
dict.put(\synthSize, 100);
dict.put(\synthColor, Color.cyan(0.8));
dict.put(\synthTypeLabelColor, Color.cyan(0.9));
dict.put(\synthTypeStringColor, Color.black);

dict;